// Carta completa del Restaurante Dai Montaña, transcrita del PDF oficial (carta-dai-montana.pdf).
const MENU = [
  {
    id: "ensaladas",
    name: "Ensaladas",
    icon: "🥗",
    items: [
      { num: "1", name: "Mixta", desc: "Escarola, tomate, pepino, atún, huevo, aceitunas y espárragos", price: 7.80 },
      { num: "2", name: "Montaña", desc: "Escarola, piña, melocotón, gambas y queso", price: 8.50 },
      { num: "3", name: "Col", desc: "Col, salsa rosa y queso", price: 5.50 },
      { num: "4", name: "Gambas y pollo", desc: "Escarola, aguacate, gambas, manzana, pollo y salsa de yogurt", price: 9.95 },
      { num: "5", name: "De la casa", desc: "Escarola, tomate, pepino, cebolla, millo, aceitunas, huevo, atún, aguacate, espárragos y gambas", price: 10.55 },
      { num: "6", name: "Tomate al ajillo con perejil", price: 5.95 },
      { num: "7", name: "Aguacate con gamba", desc: "Escarola, aguacate, gambas, naranja y salsa rosa", price: 9.95 },
    ],
  },
  {
    id: "entrantes",
    name: "Entrantes",
    icon: "🍞",
    items: [
      { num: "8", name: "Pan con Ajo", price: 1.80 },
      { num: "9", name: "Pan con Alioli", price: 1.80 },
      { num: "10", name: "Pan con Ajo y tomate", price: 2.50 },
      { num: "11", name: "Papas locas", price: 4.50 },
      { num: "12", name: "Papas Arrugadas", price: 5.50 },
      { num: "13", name: "Pimientos de Padrón", price: 6.90 },
      { num: "14", name: "Gambas al ajillo", price: 11.50 },
      { num: "15", name: "Gambas con champiñones", price: 11.90 },
      { num: "16", name: "Gambas a la plancha", price: 12.90 },
    ],
  },
  {
    id: "combinados",
    name: "Platos Combinados",
    icon: "🍽️",
    items: [
      { num: "17", name: "Tortilla española", desc: "Papas, huevo, cebolla, pimientos rojos y verdes", price: 9.50 },
      { num: "18", name: "Tortilla francesa", desc: "Huevo y perejil", price: 4.95 },
      { num: "19", name: "Papas pizza", desc: "Papas, jamón, queso y alioli", price: 7.20 },
      { num: "20", name: "Papas de la casa", desc: "Papas, escarola, jamón, queso, cebolla, salchicha, bacon y alioli", price: 8.75 },
      { num: "21", name: "Papas fingers", desc: "Papas, escarola, jamón, queso, cebolla, fingers de pollo y alioli", price: 8.95 },
      { num: "22", name: "Queso Semiduro", price: 9.50 },
      { num: "23", name: "Nuggets de pollo", price: 8.00 },
      { num: "24", name: "Fingers de pollo", price: 8.25 },
      { num: "25", name: "Salchichas", price: 8.50 },
      { num: "26", name: "Pechuga de pollo", desc: "A la plancha o empanado (+0,50€)", price: 9.80 },
      { num: "27", name: "Vuelta de ternera", desc: "A la plancha o a la casera", price: 10.60 },
      { num: "28", name: "Escalope de ternera", price: 10.90 },
      { num: "29", name: "Cerdo", desc: "Frito", price: 10.50 },
      { num: "30", name: "Chuleta de cerdo", price: 9.80 },
      { num: "31", name: "Churro de pescado", price: 9.80 },
      { num: "32", name: "Pescado (Fogonero)", desc: "A la plancha o empanado (+0,50€)", price: 11.90 },
      { num: "33", name: "Taco de pescado (Fogonero)", desc: "Frito o a la plancha", price: 11.90 },
      { num: "34", name: "Chocos", desc: "Frito o a la plancha", price: 13.90 },
      { num: "35", name: "Calamares Saharianos", desc: "Frito o a la plancha", price: 17.50 },
      { num: "36", name: "Pulpo frito", price: 13.95 },
      { num: "37", name: "Pulpo a la gallega", price: 13.95 },
    ],
  },
  {
    id: "pizzas",
    name: "Pizzas",
    icon: "🍕",
    note: "Masa casera y fresca. Base de todas las pizzas: salsa de tomate, queso y orégano. Extras: variados 0,80€ / carnes 1,50€ / mariscos 2,00€.",
    items: [
      { num: "38", name: "Tapa Pizza", desc: "3 ingredientes a elegir", price: 5.00 },
      { num: "39", name: "Pizza Mediana", desc: "3 ingredientes a elegir", price: 8.00 },
      { num: "40", name: "Calzone", desc: "2 ingredientes a elegir", price: 9.50 },
      { num: "41", name: "Margarita", desc: "Salsa de tomate, queso y orégano", price: 8.50 },
      { num: "42", name: "Cuatro Quesos", desc: "Emmendar, Cheddar, Gouda y queso curado", price: 10.00 },
      { num: "43", name: "Cuatro Estaciones", desc: "Jamón, gambas, atún, champiñones, cangrejo y aceitunas", price: 10.55 },
      { num: "44", name: "Marinera", desc: "Gambas, atún, cangrejo y mejillón", price: 10.55 },
      { num: "45", name: "Opera", desc: "Jamón y atún", price: 9.55 },
      { num: "46", name: "Barbacoa", desc: "Bacon, cebolla, salchicha y salsa barbacoa", price: 10.00 },
      { num: "47", name: "Montaña", desc: "Atún, gambas y millo", price: 10.00 },
      { num: "48", name: "Caprichosa", desc: "Jamón y champiñones", price: 9.55 },
      { num: "49", name: "Canaria", desc: "Jamón y gambas", price: 10.00 },
      { num: "50", name: "Vegetal", desc: "Champiñones, pimiento, cebolla, aceitunas, millo y espárragos", price: 10.00 },
      { num: "51", name: "Pescatora", desc: "Atún y cebolla", price: 9.55 },
      { num: "52", name: "Amapola", desc: "Jamón, pollo, gambas, atún y cebollas", price: 12.00 },
      { num: "53", name: "De la Casa", desc: "Gambas, mejillones, bacon, anchoas, huevo, pimiento y cebolla", price: 12.80 },
    ],
  },
  {
    id: "bocadillos",
    name: "Bocadillos",
    icon: "🥖",
    note: "+Normal: escarola, tomate y alioli. +Especial: Normal + jamón, queso y huevo.",
    items: [
      { num: "54A", name: "Choco Normal", desc: "Col y alioli", price: 4.55 },
      { num: "54B", name: "Choco Especial", price: 5.50 },
      { num: "55A", name: "Pechuga Plancha Normal", price: 4.25 },
      { num: "55B", name: "Pechuga Plancha Especial", price: 5.00 },
      { num: "56A", name: "Ternera Plancha Normal", price: 4.25 },
      { num: "56B", name: "Ternera Plancha Especial", price: 5.00 },
      { num: "57A", name: "Pescado Plancha Normal", price: 4.25 },
      { num: "57B", name: "Pescado Plancha Especial", price: 5.00 },
      { num: "58A", name: "Lomo Normal", price: 4.25 },
      { num: "58B", name: "Lomo Especial", price: 5.00 },
      { num: "59A", name: "Bacon Normal", price: 4.25 },
      { num: "59B", name: "Bacon Especial", price: 5.00 },
      { num: "60A", name: "Pechuga Empanada Normal", price: 4.50 },
      { num: "60B", name: "Pechuga Empanada Especial", price: 5.50 },
      { num: "61A", name: "Escalope Normal", price: 4.50 },
      { num: "61B", name: "Escalope Especial", price: 5.50 },
      { num: "62A", name: "Pescado Empanado Normal", price: 4.50 },
      { num: "62B", name: "Pescado Empanado Especial", price: 5.50 },
      { num: "63", name: "Tortilla española", price: 4.50 },
      { num: "64", name: "Tortilla francesa", price: 4.00 },
    ],
  },
  {
    id: "hamburguesas",
    name: "Hamburguesas",
    icon: "🍔",
    items: [
      { num: "65A", name: "Normal", desc: "Carne, tomate, escarola, cebolla y salsa", price: 4.95 },
      { num: "65B", name: "Especial", desc: "Normal + jamón, queso y huevo", price: 5.80 },
    ],
  },
  {
    id: "perritos",
    name: "Perritos",
    icon: "🌭",
    items: [
      { num: "66A", name: "Normal", desc: "Salchicha, cebolla y salsa", price: 3.80 },
      { num: "66B", name: "Especial", desc: "Normal + queso", price: 4.00 },
    ],
  },
  {
    id: "sandwich",
    name: "Sandwich",
    icon: "🥪",
    items: [
      { num: "67A", name: "Mixto", desc: "Jamón y queso", price: 3.00 },
      { num: "68A", name: "Atún y millo", desc: "Vegetal", price: 3.50 },
      { num: "69A", name: "Atún y huevo", desc: "Vegetal", price: 3.50 },
      { num: "70A", name: "Vegetal con gambas", price: 4.25 },
      { num: "71A", name: "Vegetal con cangrejo", price: 4.00 },
      { num: "72A", name: "Vegetal con pollo", price: 4.25 },
      { num: "73A", name: "Vegetal con tortilla francesa", price: 4.00 },
      { num: "74A", name: "Vegetal especial", price: 4.80 },
      { num: "75A", name: "Vegetal especial + papas", price: 6.50 },
    ],
  },
  {
    id: "croissant",
    name: "Croissant",
    icon: "🥐",
    items: [
      { num: "67B", name: "Mixto", desc: "Jamón y queso", price: 4.25 },
      { num: "68B", name: "Atún y millo", desc: "Vegetal", price: 4.50 },
      { num: "69B", name: "Atún y huevo", desc: "Vegetal", price: 4.50 },
      { num: "70B", name: "Vegetal con gambas", price: 5.90 },
      { num: "71B", name: "Vegetal con cangrejo", price: 5.50 },
      { num: "72B", name: "Vegetal con pollo", price: 5.00 },
      { num: "73B", name: "Vegetal con tortilla francesa", price: 4.80 },
      { num: "74B", name: "Vegetal especial", price: 5.90 },
      { num: "75B", name: "Vegetal especial + papas", price: 7.40 },
    ],
  },
  {
    id: "china-entrantes",
    name: "Comida China · Entrantes",
    icon: "🥢",
    items: [
      { num: "76", name: "Rollitos de primavera / vegetal", price: 1.60 },
      { num: "77", name: "Wantun frito", price: 4.50 },
      { num: "78", name: "Pan chino", price: 1.80 },
      { num: "79", name: "Pan de Gambas", price: 3.80 },
      { num: "80", name: "Verduras rebosadas", price: 7.80 },
      { num: "81", name: "Sopa de la casa", price: 5.50 },
      { num: "82", name: "Sopa de pollo", price: 5.00 },
      { num: "83", name: "Sopa de Wantun", price: 5.00 },
    ],
  },
  {
    id: "arroces-pasta",
    name: "Arroces y Pasta",
    icon: "🍜",
    items: [
      { num: "84", name: "Arroz 3 delicias / con soja / al curry", price: 5.50 },
      { num: "85", name: "Arroz con pollo / ternera", price: 5.80 },
      { num: "86", name: "Arroz con gambas", price: 6.80 },
      { num: "87", name: "Tallarines con verduras", price: 7.40 },
      { num: "88", name: "Tallarines con pollo / gambas", price: 8.00 },
      { num: "89", name: "Tallarines con pollo y gambas", price: 8.50 },
      { num: "90", name: "Fideos de arroz con verduras", price: 7.80 },
      { num: "91", name: "Fideos de arroz con pollo / gambas / bacon", price: 8.55 },
      { num: "92", name: "Fideos de arroz con pollo y gambas", price: 8.95 },
    ],
  },
  {
    id: "pollo-china",
    name: "Pollo (China)",
    icon: "🐔",
    items: [
      { num: "93", name: "Pollo agridulce", price: 6.95 },
      { num: "94", name: "Pollo salsa de ajo", price: 6.95 },
      { num: "95", name: "Pollo al limón", price: 6.95 },
      { num: "96", name: "Pollo con almendras", price: 7.95 },
      { num: "97", name: "Pollo con salsa picante", price: 7.95 },
      { num: "98", name: "Chop suey de pollo", price: 7.95 },
      { num: "99", name: "Pollo al curry", price: 7.95 },
    ],
  },
  {
    id: "gamba-china",
    name: "Gamba (China)",
    icon: "🍤",
    items: [
      { num: "100", name: "Gambas rebosado / salsa agridulce", price: 11.90 },
      { num: "101", name: "Gambas con almendras", price: 10.95 },
      { num: "102", name: "Gambas con salsa picante", price: 10.95 },
      { num: "103", name: "Chop suey de gambas", price: 9.95 },
    ],
  },
  {
    id: "pato",
    name: "Pato",
    icon: "🦆",
    items: [
      { num: "104", name: "Pato frito", price: 10.80 },
      { num: "105", name: "Pato salsa de naranja", price: 11.80 },
      { num: "106", name: "Pato con almendras", price: 11.80 },
    ],
  },
  {
    id: "especiales-china",
    name: "Platos Especiales",
    icon: "⭐",
    items: [
      { num: "107", name: "Pollo salsa de ostras", price: 8.50 },
      { num: "108", name: "Pollo con puerros (plancha)", price: 9.50 },
      { num: "109", name: "Gambas a la plancha", price: 12.90 },
      { num: "110", name: "Pato salsa Hoi-sin (plancha)", price: 12.90 },
      { num: "111", name: "Plancha de la casa", price: 14.90 },
      { num: "112", name: "Entrecot fresco con salsa china (plancha)", desc: "Preguntar al camarero si hay disponibilidad", price: 18.90 },
    ],
  },
  {
    id: "menus",
    name: "Menús",
    icon: "📋",
    items: [
      { num: "M1", name: "Menú 1", desc: "Pizza con 3 ingredientes a elegir · Pan con ajo o 1/2 ración de papas · Refresco de lata · Helado o café", price: 10.50 },
      { num: "M2", name: "Menú 2", desc: "2 pizzas con 3 ingredientes a elegir · 1 ración de papas · Refresco de 1,5 litro", price: 18.90 },
      { num: "M3", name: "Menú 3", desc: "A elegir entre bocadillo, sandwich o croissant · Acompañado de papas · Refresco de lata · Helado o café", price: 9.50 },
    ],
  },
  {
    id: "refrescos",
    name: "Refrescos",
    icon: "🥤",
    items: [
      { name: "Coca-Cola", price: 1.60 },
      { name: "Fanta", price: 1.60 },
      { name: "Clipper", price: 1.60 },
      { name: "7up", price: 1.60 },
      { name: "Schweppes", price: 1.60 },
      { name: "Nestea", price: 2.00 },
      { name: "Aquarius", price: 2.00 },
      { name: "Appleteiser", price: 2.00 },
      { name: "Tónica", price: 2.00 },
      { name: "Redbull", price: 2.50 },
      { name: "Monster", price: 2.50 },
    ],
  },
  {
    id: "agua",
    name: "Agua",
    icon: "💧",
    items: [
      { name: "Vaso", price: 0.40 },
      { name: "Botella pequeña (33cl)", price: 1.20 },
      { name: "Botella grande (1,5l)", price: 1.80 },
    ],
  },
  {
    id: "zumos",
    name: "Zumos",
    icon: "🧃",
    items: [
      { name: "Pera Piña", price: 1.60 },
      { name: "Melocotón", price: 1.60 },
      { name: "BioFrutas (Tropical)", price: 1.80 },
      { name: "Naranja Natural", price: 3.00 },
    ],
  },
  {
    id: "cervezas",
    name: "Cervezas",
    icon: "🍺",
    items: [
      { name: "Tropical", price: 1.80 },
      { name: "Botellín", price: 1.20 },
      { name: "Heineken", price: 1.80 },
      { name: "Dorada Sin", price: 1.80 },
      { name: "Dorada especial", price: 2.00 },
      { name: "Estrella Galicia (0,25)", price: 1.50 },
      { name: "1906", price: 2.50 },
      { name: "1924", price: 2.50 },
      { name: "Smirnoff Ice", price: 3.50 },
    ],
  },
  {
    id: "vino",
    name: "Vino",
    icon: "🍷",
    items: [
      { name: "Copa El Coto", price: 3.00 },
      { name: "El Coto (tinto, botella)", price: 11.00 },
      { name: "Copa Ramón Bilbao", price: 4.00 },
      { name: "Ramón Bilbao (tinto, botella)", price: 15.50 },
      { name: "Copa Protos", price: 4.00 },
      { name: "Protos (tinto, botella)", price: 15.50 },
      { name: "Copa San Valentín", price: 3.50 },
      { name: "San Valentín (semi, botella)", price: 13.00 },
      { name: "Copa Viña Sol", price: 3.50 },
      { name: "Viña Sol (seco, botella)", price: 13.50 },
      { name: "Yaiza (semi o seco, botella)", price: 29.50 },
    ],
  },
  {
    id: "whisky",
    name: "Whisky",
    icon: "🥃",
    items: [
      { name: "Haig", price: 2.50 },
      { name: "JB", price: 2.50 },
      { name: "100 Pipers", price: 2.50 },
      { name: "Etiqueta Roja", price: 3.00 },
      { name: "Etiqueta Negra", price: 4.50 },
      { name: "Etiqueta Verde", price: 9.00 },
      { name: "Jack Daniels", price: 4.50 },
      { name: "Chivas", price: 4.50 },
      { name: "Cardhu", price: 5.00 },
      { name: "Ballantines", price: 3.00 },
    ],
  },
  {
    id: "vodka",
    name: "Vodka",
    icon: "🍸",
    items: [
      { name: "Moskovskaya", price: 2.50 },
      { name: "Smirnoff", price: 2.80 },
    ],
  },
  {
    id: "licores",
    name: "Licores",
    icon: "🍹",
    items: [
      { name: "Jägermeister", price: 4.00 },
      { name: "Ruavieja", price: 4.00 },
      { name: "Amareto", price: 4.00 },
      { name: "Vodka Caramelo", price: 3.00 },
      { name: "Ron miel", price: 3.00 },
      { name: "Frangelico", price: 4.00 },
      { name: "Baileys", price: 4.00 },
      { name: "Tía María", price: 4.00 },
      { name: "Licor 43", price: 4.00 },
      { name: "Koyak", price: 3.00 },
    ],
  },
  {
    id: "ron",
    name: "Ron",
    icon: "🥂",
    items: [
      { name: "Telde (blanco)", price: 2.00 },
      { name: "Arehucas (oro-blanco)", price: 2.00 },
      { name: "Artemi (oro-blanco)", price: 2.00 },
      { name: "Aldea (blanco)", price: 2.80 },
      { name: "Santa Teresa", price: 3.00 },
      { name: "Brugal Añejo", price: 4.00 },
      { name: "Cacique 500", price: 4.50 },
      { name: "Malibu", price: 3.00 },
      { name: "Barceló Añejo", price: 3.50 },
      { name: "Havana 3 años", price: 2.50 },
      { name: "Havana 5 años", price: 2.80 },
      { name: "Havana 7 años", price: 3.00 },
      { name: "Matuzalem 7 años", price: 4.00 },
      { name: "Matuzalem 15 años", price: 5.00 },
      { name: "Zacapa 23 años", price: 9.50 },
    ],
  },
  {
    id: "ginebra",
    name: "Ginebra",
    icon: "🍋",
    items: [
      { name: "Gordons", price: 2.50 },
      { name: "Beefeater", price: 3.00 },
      { name: "Beefeater 24", price: 4.50 },
      { name: "Puerto de Indias", price: 3.00 },
      { name: "Bombay", price: 4.00 },
      { name: "Carmela", price: 4.00 },
      { name: "Tanqueray", price: 4.50 },
    ],
  },
];

// Asigna un id único a cada plato para usarlo como clave del carrito.
MENU.forEach((cat) => {
  cat.items.forEach((item, idx) => {
    item.id = `${cat.id}-${item.num || idx}`;
    item.category = cat.name;
  });
});
